spring.application.name=webapp
server.port=8080

# ================================
# H2 Console (siempre disponible)
# ================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ================================
# MySQL - Datasource principal
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/estudia_ya?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=



# ================================
# JPA Configuration
# ================================
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ================================
# AI Configuration
# ================================
app.ai.provider=groq
app.ai.custom.groq.api-key=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
app.ai.custom.groq.model=llama-3.1-8b-instant

# ================================
# JWT Configuration
# ================================
app.jwt.secret=estudiaya-dev-secret-change-me
app.jwt.expiration-ms=86400000

# Angular local
app.frontend.login-url=http://localhost:4200/login
