spring.application.name=webapp

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=123

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA Configuration

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


app.ai.provider=groq
app.ai.custom.groq.api-key=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
app.ai.custom.groq.model=llama-3.1-8b-instant